version: '3.8'
services:
  elasticsearch:
    build:
      context: .
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - node.name=es-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9208:9200"
      - "9308:9300"
volumes:
  es_data:
    driver: local
